version: "3.8"

services:
  android-builder:
    build:
      context: .
      dockerfile: dockerfile
    container_name: appmobile1
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    restart: "no"

volumes:
  jenkins_home:
