version: "3.8"

services:
  android-builder:
    build:
      context: .
      # Pastikan nama file ini sesuai dengan file Dockerfile Anda
      dockerfile: dockerfile.txt 
    # Nama container disesuaikan dengan yang Anda panggil di Jenkinsfile
    container_name: appmobile1
    working_dir: /workspace
    volumes:
      # Mount kode dari host Jenkins ke /workspace di container
      - .:/workspace
    # Perintah ini membuat container tetap menyala agar bisa di-'exec'
    command: tail -f /dev/null
    restart: "no"

# Volume jenkins_home dihapus karena servis jenkins sudah dihapus
volumes: {}
