version: "3.8"

services:
  jenkins:
    image: new_cloudcomp_jenkins_1
    container_name: new_cloudcomp_jenkins_1
    user: root
    ports:
      - "8667:8666"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker  
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

  android-builder:
    build:
      context: .
      dockerfile: dockerfile
    container_name: android-builder1
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    depends_on:
      - jenkins
    restart: "no"

volumes:
  jenkins_home:
