version: "3.8"

services:
 android-builder:
    build:
      context: .
      dockerfile: dockerfile.txt # Sesuaikan nama file Dockerfile Anda
    container_name: appmobile1  # <-- UBAH NAMA INI
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null # Perintah ini agar container tetap hidup
    restart: "no"

# Volume 'jenkins_home' tidak diperlukan lagi
volumes: {}
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

  android-builder:
    build:
      context: .
      dockerfile: dockerfile
    container_name: android-builder1
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    depends_on:
      - jenkins
    restart: "no"

volumes:
  jenkins_home:
